# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    volumes:
      - ./autogpt:/app
      - .env:/app/.env
      - ./data/workspace:/home/appuser/auto_gpt_workspace:rw
    profiles: ["exclude-from-up"]

  redis:
    #
    # image: "redis/redis-stack-server:latest"
    # Stack lets use the fancy ui to see the data in redis
    image: "redis/redis-stack:latest"
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
      - 8001:8001

